Repository rahataid/rahat-ui, pull requests merged in 2025-07, with the labels that each got.

#1419 action: Stakeholders add searchable Support Area tags, update tables & forms per new design
  apps/rahat-ui/public/files/stakeholder-sample.xlsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/[stakeholdersId]/edit/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/[stakeholdersId]/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/add/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/groups/add/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/groups/edit/[editId]/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/import/page.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholder.groups.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholders.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/columns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/component/stakeholders.table.filters.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/edit.stakeholder.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/import.stakeholders.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/staholders.info.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/stakeholders.groups.details.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/stakeholders.view.tsx
  libs/query/src/lib/aa/stakeholders/stakeholders.service.ts
Labels: enhancement, deployed to dev

#1423 audio record features implementation
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/components/recorder.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/edit.communication.form.tsx
Labels: enhancement

#1490 feedback on the core and project
  apps/rahat-ui/src/sections/beneficiary/beneficiary.layout.tsx
  apps/rahat-ui/src/sections/beneficiary/beneficiaryDetail.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/beneficiariesGroupTable.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
  apps/rahat-ui/src/sections/users/user.layout.tsx
  apps/rahat-ui/src/sections/vendors/vendors.layout.tsx
Labels: deployed to dev

#1496 AA: Apply dhm data modification
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/info.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.monitor.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/rainfall.watch.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/river.watch.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dhm/water.level.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/river.watch.details.tsx
Labels: deployed to dev

#1508 784 aa project vendor details page feedbacks
  apps/rahat-ui/src/sections/projects/aa-2/dashboard/main.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefTransactionDetails/infoItem.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/columns/useTransactionColumns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/components/overview.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/components/profile.card.tsx
  apps/rahat-ui/src/utils/string.ts
  libs/query/src/config.ts
  libs/query/src/lib/projects/projects.service.ts
Labels: deployed to dev

#1486 593 optimization enhance system performance and efficiency project aa
  apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
  libs/query/src/lib/aa/activities/activities.service.ts
Labels: deployed to dev
