Repository rahataid/rahat-ui, pull requests merged in 2025-05, with the labels that each got.

#1345 AA: Revert phase
  apps/rahat-ui/src/common/custom.alert.dialog.tsx
  apps/rahat-ui/src/common/icon.label.btn.tsx
  apps/rahat-ui/src/common/index.ts
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.tabs.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
  libs/query/src/lib/aa/phases/phases.service.ts
  libs/shadcn/src/components/ui/alert-dialog.tsx
Labels: enhancement

#1343 Feedback bug updated features
  apps/rahat-ui/public/files/stakeholder-sample.xlsx
  apps/rahat-ui/src/common/search.input.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/edit.communication.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsActivitesTableColumns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/fundManagement/components/token.overview.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholder.groups.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/import.stakeholders.tsx
  libs/query/src/lib/aa/activities/activities.service.ts
  libs/query/src/lib/aa/groups/groups.service.ts
Labels: bug, enhancement

#1352 Fixed bugs and feedback
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.communication.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/list/daily.monitoring.list.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholder.groups.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholders.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/import.stakeholders.tsx
Labels: deployed to dev
