Repository rahataid/rahat-ui, pull requests merged in 2025-06, with the labels that each got.

#1368 fix: Phone number country code should be default selected as +977 and…
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholders.tsx
  libs/shadcn/src/components/ui/phone-input.tsx
Labels: deployed to dev

#1344 AA: Integrate payout sections
  apps/rahat-ui/src/sections/projects/aa-2/dashboard/project.Dashboard.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/useBeneficiaryGroupDetailsLogColumns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/component/recent.payout.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/beneficiariesGroupTable.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.dialog.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/useBeneficiariesGroupTablecolumn.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/main.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/table/payoutTransactionList.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/table/usePayoutTransactionLogTableColumn.tsx
  libs/query/src/config.ts
  libs/query/src/lib/aa/funManagement/service.ts
  libs/query/src/lib/aa/index.ts
  libs/query/src/lib/aa/payout/index.ts
  libs/query/src/lib/aa/payout/payout.service.ts
  libs/query/src/lib/projects/projects.service.ts
Labels: enhancement

#1379 Aa figma changes bugs feedback
  apps/rahat-ui/src/common/header.with.back.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/components/documentCard.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/details/activity.detail.cards.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/edit.communication.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/comms.logs.detail.page.tsx
  apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/communication.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/communicationLog/details/view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/fundManagement/details.tsx
  apps/rahat-ui/src/sections/projects/aa-2/fundManagement/tables/fm.detail.table.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/benefGroupDetails/details.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/payout/initiatePayout/payment.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/add.stakeholder.groups.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/stakeholders.groups.details.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.phase.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/main.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/manage.threshold.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/columns/useRedemptionRequest.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/components/overview.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/components/profile.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/components/transaction.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/detail.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/main.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/table.columns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/beneficiary.table.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/redemption.request.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/tables/transactions.history.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/tabs/vendor.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/tabs/vendor.redemption.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/vendor/types/index.ts
  package.json
Labels: deployed to dev

#1387 integration of revert phase get one and implementation and bug fix
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/details/update.activity.status.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/list/useActivitiesTableColumn.tsx
  apps/rahat-ui/src/sections/projects/aa-2/communicationLog/table/useCommsActivitesTableColumns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useDailyMonitoringTableColumn.tsx
  apps/rahat-ui/src/sections/projects/aa-2/fundManagement/columns/useFMColumns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/activate.trigger.dialog.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/automated.trigger.add.form.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.tabs.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/detail.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/edit.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/phase.detail.tsx
  apps/rahat-ui/src/utils/file.validation.ts
  libs/query/src/lib/aa/phases/phases.service.ts
  libs/query/src/lib/aa/trigger-statements/trigger-statements.service.ts
Labels: bug, enhancement, deployed to dev

#1393 Daily monitoring activity trigger
  apps/rahat-ui/src/sections/projects/aa-2/activities/add/add.activity.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/activities/edit/activity.edit.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.another.data.source.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/add/add.daily.monitoring.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/edit/edit.daily.monitoring.view.tsx
  apps/rahat-ui/src/sections/projects/aa-2/dataSources/components/dailyMonitoring/useSelectItems.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/dynamic.triggers.list.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/trigger.card.tsx
  apps/rahat-ui/src/sections/projects/aa-2/triggerStatement/components/triggers.list.card.tsx
  apps/rahat-ui/src/utils/fieldLabelValidation.ts
  pnpm-lock.yaml
Labels: deployed to dev

#1409 allowed to enter the plus sign before the phone number while adding and editing benef in community tool
  apps/community-tool-ui/src/sections/beneficiary/add/addBeneficiary.tsx
  apps/community-tool-ui/src/sections/beneficiary/editBeneficiary.tsx
  package.json
  pnpm-lock.yaml
Labels: deployed to dev

#1407 fix: role protection on stakeholders group details page and its subpages
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/groups/add/page.tsx
  apps/rahat-ui/src/app/projects/aa/[id]/stakeholders/groups/edit/[editId]/page.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/columns.tsx
  apps/rahat-ui/src/sections/projects/aa-2/stakeholders/stakeholders.groups.details.tsx
Labels: deployed to dev
